source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib", :require => "sinatra/reloader"
gem "sinatra-activerecord"
gem "rake"
gem "pg"
gem "pry"

group :test do
  gem 'capybara', require: 'capybara/rspec'
  gem "rspec"
  gem "shoulda-matchers"
end
